"""Team invitations

Revision ID: 3ae355a3c419
Revises: 3b5f64f1ca1a
Create Date: 2022-10-11 23:38:46.975456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae355a3c419'
down_revision = '3b5f64f1ca1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('team_role', sa.Enum('owner', 'member', name='teamroles'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=True)
    op.create_index(op.f('ix_invitation_id'), 'invitation', ['id'], unique=False)
    op.add_column('user', sa.Column('team_role', sa.Enum('owner', 'member', name='teamroles'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team_role')
    op.drop_index(op.f('ix_invitation_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_table('invitation')
    # ### end Alembic commands ###
