"""Handoff and restrictions for schedule layer

Revision ID: 3bf9b7d27020
Revises: 51e40eb7e927
Create Date: 2022-12-03 23:31:01.007812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf9b7d27020'
down_revision = '51e40eb7e927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer', sa.Column('handoff_time', sa.Time(), nullable=True))
    op.add_column('layer', sa.Column('restriction_day_start', sa.Time(), nullable=True))
    op.add_column('layer', sa.Column('restriction_day_end', sa.Time(), nullable=True))
    op.add_column('layer', sa.Column('restriction_week_start', sa.DateTime(), nullable=True))
    op.add_column('layer', sa.Column('restriction_week_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer', 'restriction_week_end')
    op.drop_column('layer', 'restriction_week_start')
    op.drop_column('layer', 'restriction_day_end')
    op.drop_column('layer', 'restriction_day_start')
    op.drop_column('layer', 'handoff_time')
    # ### end Alembic commands ###
