"""Schedules

Revision ID: 4c3e9f291e66
Revises: 76a2c9b52a7a
Create Date: 2022-11-04 22:54:23.514720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3e9f291e66'
down_revision = '76a2c9b52a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_id'), 'schedule', ['id'], unique=False)
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rotation_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layer_id'), 'layer', ['id'], unique=False)
    op.create_table('layer_users',
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('schedule_layers',
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('layer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_layers')
    op.drop_table('layer_users')
    op.drop_index(op.f('ix_layer_id'), table_name='layer')
    op.drop_table('layer')
    op.drop_index(op.f('ix_schedule_id'), table_name='schedule')
    op.drop_table('schedule')
    # ### end Alembic commands ###
