"""Schedule layers on delete cascade

Revision ID: 51e40eb7e927
Revises: 4c3e9f291e66
Create Date: 2022-11-28 17:22:16.181754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e40eb7e927'
down_revision = '4c3e9f291e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_layers')
    op.drop_constraint('layer_schedule_id_fkey', 'layer', type_='foreignkey')
    op.create_foreign_key(None, 'layer', 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'layer', type_='foreignkey')
    op.create_foreign_key('layer_schedule_id_fkey', 'layer', 'schedule', ['schedule_id'], ['id'])
    op.create_table('schedule_layers',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], name='schedule_layers_layer_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='schedule_layers_schedule_id_fkey')
    )
    # ### end Alembic commands ###
