"""Customer pk is user id

Revision ID: 5f3eefdda4b1
Revises: 3e8ee2e89ded
Create Date: 2023-01-27 19:43:50.333454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3eefdda4b1'
down_revision = '3e8ee2e89ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE customer DROP CONSTRAINT customer_pkey')
    op.alter_column('customer', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_primary_key('customer_pkey', 'customer', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_primary_key('customer_pkey', 'customer', ['stripe_custmer_id'])
    # ### end Alembic commands ###
