"""Initial postgres migration

Revision ID: 703bd77c5625
Revises: 
Create Date: 2022-10-08 23:11:05.538686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703bd77c5625'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('slack_bot_token', sa.String(), nullable=True),
    sa.Column('slack_channel', sa.String(), nullable=True),
    sa.Column('slack_incoming_webhook', sa.String(), nullable=True),
    sa.Column('slack_team_name', sa.String(), nullable=True),
    sa.Column('telegram_random_string', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('telegram_chat_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_id'), 'integration', ['id'], unique=False)
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('monitor_type', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('periodicity', sa.Integer(), nullable=True),
    sa.Column('request_timeout', sa.Integer(), nullable=True),
    sa.Column('http_method', sa.String(length=8), nullable=True),
    sa.Column('request_body', sa.String(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('follow_redirects', sa.Boolean(), nullable=True),
    sa.Column('keep_cookies_between_redirects', sa.Boolean(), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=True),
    sa.Column('ssl_check_expiration', sa.Integer(), nullable=True),
    sa.Column('auth_user', sa.String(), nullable=True),
    sa.Column('auth_pass', sa.String(), nullable=True),
    sa.Column('num_pings', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('recovery_period', sa.Integer(), nullable=True),
    sa.Column('confirmation_period', sa.Integer(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_id'), 'monitor', ['id'], unique=False)
    op.create_table('statuspage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('company_website', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statuspage_id'), 'statuspage', ['id'], unique=False)
    op.create_index(op.f('ix_statuspage_subdomain'), 'statuspage', ['subdomain'], unique=True)
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('cause', sa.String(), nullable=True),
    sa.Column('request', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_id'), 'incident', ['id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('monitored_at', sa.DateTime(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=False)
    op.create_table('statuspage_monitor',
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('statuspage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['statuspage_id'], ['statuspage.id'], )
    )
    op.create_table('incidentevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('extra_field', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidentevent')
    op.drop_table('statuspage_monitor')
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_incident_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_statuspage_subdomain'), table_name='statuspage')
    op.drop_index(op.f('ix_statuspage_id'), table_name='statuspage')
    op.drop_table('statuspage')
    op.drop_index(op.f('ix_monitor_id'), table_name='monitor')
    op.drop_table('monitor')
    op.drop_index(op.f('ix_integration_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
