"""Add invitation hash

Revision ID: 76a2c9b52a7a
Revises: 3ae355a3c419
Create Date: 2022-10-22 21:34:14.876497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a2c9b52a7a'
down_revision = '3ae355a3c419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('invitation_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'invitation_hash')
    # ### end Alembic commands ###
