"""Incident acknowledge

Revision ID: b3d933975a8d
Revises: 3bf9b7d27020
Create Date: 2022-12-26 20:21:54.715457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d933975a8d'
down_revision = '3bf9b7d27020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('incident', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incident', 'user', ['acknowledged_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_column('incident', 'acknowledged_by')
    op.drop_column('incident', 'acknowledged_at')
    # ### end Alembic commands ###
